<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Terminal Exceptions</name>
   <tag></tag>
   <elementGuidId>b30423a6-85a9-44c1-bb41-eb09b7ce9818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r23:']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.font-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e199e194-9420-4467-bfff-b136c4851067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal</value>
      <webElementGuid>bdd1a98b-1c78-41a2-8986-103f61f58faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terminal Exceptions</value>
      <webElementGuid>5f93bbc4-6cb5-4749-9b6b-49197fcf809d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r23:&quot;)/span[@class=&quot;font-normal&quot;]</value>
      <webElementGuid>931730af-1d7c-4385-8c5d-07e4bba3f2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r23:']/span</value>
      <webElementGuid>96c9f31b-e032-4c69-bb54-8c835470941d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'radix-:r23:', '&quot;', ')/span[@class=', '&quot;', 'font-normal', '&quot;', ']')])[1]/following::span[1]</value>
      <webElementGuid>d4dfcecd-1382-471a-89be-0306b7bc18e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip Exceptions'])[2]/preceding::span[1]</value>
      <webElementGuid>3d0d9dd5-4653-4a38-b27b-51b4f02c1bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Exceptions'])[1]/preceding::span[2]</value>
      <webElementGuid>632c9a47-15b3-4b92-8ac5-0441b28eb661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/span</value>
      <webElementGuid>af5e87fa-3e26-4f94-9b85-8aa842a181f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Terminal Exceptions' or . = 'Terminal Exceptions')]</value>
      <webElementGuid>a9654488-50bf-4055-bcf2-2b4e7a66e3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
