<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply Filter</name>
   <tag></tag>
   <elementGuidId>f9b1140b-448c-49d1-b11b-ed72598f061c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply Filter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8a6ed73-61e4-403a-b865-f2ffa58a81cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-focus-auto mantine-active w-1/2 font-medium m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root</value>
      <webElementGuid>11a117a0-f2a1-4e6d-ac8c-b60825a6171c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9c116a3-e9f1-467b-a80e-61a417832bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Filter</value>
      <webElementGuid>3be37706-4e30-464b-8c25-132f5578a843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-4k7zqr0r4-body&quot;)/div[@class=&quot;h-screen&quot;]/div[@class=&quot;flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-row pt-4 space-x-4 w-full&quot;]/button[@class=&quot;mantine-focus-auto mantine-active w-1/2 font-medium m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root&quot;]</value>
      <webElementGuid>31c7f85c-2b7d-4977-ba8f-9b72a85f894a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>609dc920-3b74-4fe3-b881-46e167253ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-4k7zqr0r4-body']/div/div/div[2]/button[2]</value>
      <webElementGuid>2261d9fe-9480-460b-810c-c5147b03a22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Filter'])[1]/following::button[1]</value>
      <webElementGuid>7ef67a74-3813-488e-b222-c16105f8feba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GMO NORTH ZONE'])[1]/preceding::button[1]</value>
      <webElementGuid>788ae364-207e-40b3-82bd-c392f7582d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>f6411382-13b8-4683-b234-95d8d56bbd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply Filter' or . = 'Apply Filter')]</value>
      <webElementGuid>095e4c28-7e37-4477-9099-369d871061fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
