<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filters</name>
   <tag></tag>
   <elementGuidId>cbf2dda0-08d7-48a1-84f4-f92a3bf06cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-focus-auto.mantine-active.font-medium.m-77c9d27d.mantine-Button-root.m-87cf2631.mantine-UnstyledButton-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c37cf14b-f810-4e5e-b277-ed1356c8da7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-focus-auto mantine-active font-medium m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root</value>
      <webElementGuid>8241d1bd-cc7e-4588-83f1-d8e90d7f6077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>light</value>
      <webElementGuid>6549a9e4-0c8f-4ead-9639-b334f3eb962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-with-left-section</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c8995ed-fd3a-4696-bcaa-7d861212adf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1eb4e1e-d012-4592-9c0a-3e9b6eb6e520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>82132ed4-fc43-4362-820b-67f3b0437363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;pl-[76px] pb-8&quot;]/div[@class=&quot;bg-white shadow-sm sticky top-0 z-50 px-4 py-3 flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-row justify-between items-center space-x-4&quot;]/div[@class=&quot;flex flex-row justify-end items-end space-x-4&quot;]/button[@class=&quot;mantine-focus-auto mantine-active font-medium m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root&quot;]</value>
      <webElementGuid>8ee0424b-8a21-4f97-a973-a5f9a132dea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>e4799834-b671-42cb-ac60-ca523ad516a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>f488f237-90d1-4360-8984-752ec7062aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminals'])[2]/following::button[1]</value>
      <webElementGuid>9a58764d-708e-4ae6-981a-e6228d7f307b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP'])[1]/following::button[1]</value>
      <webElementGuid>04bffb68-6365-4ff2-ac8d-45c5cbc1542f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.No'])[1]/preceding::button[2]</value>
      <webElementGuid>6f99aa64-8427-4748-81a0-a149775111d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>76ee89a9-23ab-4089-8c33-caf75bd1a84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>154985b9-96b4-418c-8015-1a1c820f97e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
