<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filters_m-8fb7ebe7 mantine-Input-input</name>
   <tag></tag>
   <elementGuidId>c8e367a5-62ec-4634-86e5-9abe13601b04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.m-8fb7ebe7.mantine-Input-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter search term&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ff39ffe-7c8b-45cd-b78d-8c0786f09efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-8fb7ebe7 mantine-Input-input</value>
      <webElementGuid>9ef0182b-1dfe-45c7-abc5-8ebe9afabf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>filled</value>
      <webElementGuid>505e556d-384e-49f5-b136-3c0e240b12a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter search term</value>
      <webElementGuid>2dd1aeec-7a07-46c4-b184-316154e5241a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>87005d3c-05ff-42e6-8180-ae3929f6f203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;pl-[76px] pb-8&quot;]/div[@class=&quot;bg-white shadow-sm sticky top-0 z-50 px-4 py-3 flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-row justify-between items-center space-x-4&quot;]/div[@class=&quot;flex flex-row justify-end items-end space-x-4&quot;]/div[@class=&quot;w-60 m-6c018570 mantine-Input-wrapper&quot;]/input[@class=&quot;m-8fb7ebe7 mantine-Input-input&quot;]</value>
      <webElementGuid>6d865967-a693-4cd1-8507-8b2035deb196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>2508f3ee-cfd5-45d4-a6a5-458ea760c6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b82aec5-49ac-43b3-aa03-7bf5cf245212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter search term']</value>
      <webElementGuid>ae720349-17b7-460d-b227-27dce94af3bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
