<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Filters</name>
   <tag></tag>
   <elementGuidId>ba09ed57-039e-4cdf-9877-4d805bd0050e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.m-811560b9.mantine-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div[2]/button/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7054e1ca-12de-49e2-8578-fcadee5db5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-811560b9 mantine-Button-label</value>
      <webElementGuid>de278f02-3414-45db-abd0-09a3c8730470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>ad32a2ff-821e-4155-adb9-8b6f2eb241d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;pl-[76px] pb-8&quot;]/div[1]/div[@class=&quot;bg-white shadow-sm sticky top-0 z-50 px-4 py-3 flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-row justify-between items-center space-x-4&quot;]/div[@class=&quot;flex flex-row space-x-4 items-center&quot;]/button[@class=&quot;mantine-focus-auto mantine-active font-medium m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root&quot;]/span[@class=&quot;m-80f1301b mantine-Button-inner&quot;]/span[@class=&quot;m-811560b9 mantine-Button-label&quot;]</value>
      <webElementGuid>3406c17f-ff59-4af2-9d7d-38fbabc926de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div[2]/button/span/span[2]</value>
      <webElementGuid>35770688-a79d-4ba9-8fa0-d0ebbd7e83e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::span[3]</value>
      <webElementGuid>6c5dd427-de7c-4d21-9fa8-5dc4694d6d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[4]</value>
      <webElementGuid>15b64557-f474-472e-948e-1e93b3886bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total FAN'])[1]/preceding::span[1]</value>
      <webElementGuid>76744d2e-d33d-4aa5-9aa9-6253c5f83888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Invoice'])[1]/preceding::span[1]</value>
      <webElementGuid>c2ea0929-2b52-4e7f-85ee-b3c96cffbe28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>f238ecd4-1479-4dc3-854e-1da6861316d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>10fec0a7-2358-4ace-b056-a693a3a2f4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>7070ab28-78ef-4f50-af87-8ac36b785f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
