<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Terminal Exceptions (1)</name>
   <tag></tag>
   <elementGuidId>3628c0f3-2fe4-4383-9852-f479863924a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.font-normal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rmd:']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Terminal Exceptions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3cc115c-244f-4215-9578-794dc8e9f3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal</value>
      <webElementGuid>9e8b792d-235f-41dd-9a8b-b67cd31989c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terminal Exceptions</value>
      <webElementGuid>f0ca2e74-411d-4c5c-baf4-5c3c4072b06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rmd:&quot;)/span[@class=&quot;font-normal&quot;]</value>
      <webElementGuid>06d50350-1471-4e1c-ab05-223000b6fc42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rmd:']/span</value>
      <webElementGuid>c2015c11-b7a8-4c15-bd28-34b6031f1493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip Exceptions'])[2]/preceding::span[1]</value>
      <webElementGuid>9ff72e26-0eee-465e-a7c9-28b2a9418b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Exceptions'])[1]/preceding::span[2]</value>
      <webElementGuid>3498fb85-aeee-40df-9170-70fe82ff8003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terminal Exceptions']/parent::*</value>
      <webElementGuid>7de9dbec-4dec-48f0-87b8-37b6f7a1fd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/span</value>
      <webElementGuid>0b40a194-9bb9-4586-bf52-beb119b642e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Terminal Exceptions' or . = 'Terminal Exceptions')]</value>
      <webElementGuid>543e61c5-f1cc-474e-b2c1-0545039c5e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
