<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>2a034a60-8766-4aad-98b7-b2afd86d0667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > button.mantine-focus-auto.mantine-active.m-77c9d27d.mantine-Button-root.m-87cf2631.mantine-UnstyledButton-root > span.m-80f1301b.mantine-Button-inner > span.m-811560b9.mantine-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-a3311mv45-dropdown']/div/div[4]/div/button/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e1c5fae-967f-494b-9f14-caf3393896fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-811560b9 mantine-Button-label</value>
      <webElementGuid>f0ef1063-f6b8-45b5-8ae9-f267ab0e426e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>71756364-dc00-4b42-908e-c1d26c86a984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-a3311mv45-dropdown&quot;)/div[@class=&quot;p-2 flex flex-col justify-center items-center space-y-2&quot;]/div[@class=&quot;flex flex-col space-y-2 pt-2&quot;]/div[1]/button[@class=&quot;mantine-focus-auto mantine-active m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root&quot;]/span[@class=&quot;m-80f1301b mantine-Button-inner&quot;]/span[@class=&quot;m-811560b9 mantine-Button-label&quot;]</value>
      <webElementGuid>60800230-77bb-48ed-9a4f-4287cf5a9636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-a3311mv45-dropdown']/div/div[4]/div/button/span/span[2]</value>
      <webElementGuid>4180fbce-b65d-44b0-82c4-55899b2becaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super Admin'])[1]/following::span[3]</value>
      <webElementGuid>efe4dadb-1693-4907-befe-d0b42de59403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mallika PK'])[1]/following::span[4]</value>
      <webElementGuid>3d20f42c-6847-487f-80bc-96807cd35866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>d268f98f-7907-4ab4-ac31-0d7360b56efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span/span[2]</value>
      <webElementGuid>02d93315-dbfb-4cbd-8a37-d1fa94c503bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>b254207a-3602-403f-a647-ac99c4cdd836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
