<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Countries</name>
   <tag></tag>
   <elementGuidId>85f1a823-9c81-485a-9829-d7a9406f3235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/a[8]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Countries&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>86bf1a50-148f-4ce5-a460-86e45477c5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal</value>
      <webElementGuid>585136c1-d827-457e-a64f-07afd5179bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Countries</value>
      <webElementGuid>538bd7ef-9552-4c06-8d5e-9b6b8541b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;pl-[76px] pb-8&quot;]/div[@class=&quot;w-full flex flex-col&quot;]/div[@class=&quot;sticky top-0 left-0 right-0 z-50 bg-white pt-2 shadow-sm flex flex-col space-y-2&quot;]/div[@class=&quot;w-full h-full flex items-end justify-start pl-4 space-x-6&quot;]/a[@class=&quot;text-sm font-medium underline-offset-[10px] py-1.5 border-b-[2.5px] border-white no-underline&quot;]/div[1]/span[@class=&quot;font-normal&quot;]</value>
      <webElementGuid>06c5e82f-82f9-44fb-9035-12bc7e23bdd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/a[8]/div/span</value>
      <webElementGuid>ef9539ff-c2b5-436c-8c23-e1e747815dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Truck VTS'])[1]/following::span[1]</value>
      <webElementGuid>d248f4ed-5ff6-4da6-8449-43111306e417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trucks'])[1]/following::span[2]</value>
      <webElementGuid>9adfbc36-31b3-4e91-bbd7-9153bdaf08ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zones'])[1]/preceding::span[1]</value>
      <webElementGuid>096f98ea-f88b-4044-8836-7914a4305a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='States'])[1]/preceding::span[2]</value>
      <webElementGuid>f79228d9-c210-4375-b212-c4a357bca6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Countries']/parent::*</value>
      <webElementGuid>15a3671c-390e-4ad7-a14b-c47c33234454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]/div/span</value>
      <webElementGuid>b2a06445-1a24-44c3-9fc5-23b7d9b45043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Countries' or . = 'Countries')]</value>
      <webElementGuid>c15cffbd-f940-4fcf-9459-bf90abb56c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
