<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MP</name>
   <tag></tag>
   <elementGuidId>420aa860-8ffb-4ac8-b850-326c620557f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.m-104cd71f.mantine-Avatar-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[4]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;MP&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06d79e72-ca62-46af-ab6a-136e14413961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-104cd71f mantine-Avatar-placeholder</value>
      <webElementGuid>be92a3e2-7cc2-4823-83b2-0ce70fd052a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mallika PK</value>
      <webElementGuid>0f624d50-edfa-4a63-81d1-7322346244a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MP</value>
      <webElementGuid>8148e65c-ddf0-4f4d-b682-6b9d16220d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;flex fixed flex-col w-[76px] h-screen top-0 bottom-0 left-0 bg-primary-500 z-50 shadow-soft&quot;]/div[@class=&quot;w-full flex flex-col items-center space-y-2 py-2&quot;]/div[@class=&quot;cursor-pointer border-4 border-white border-opacity-25 rounded-full&quot;]/div[@class=&quot;m-f85678b6 mantine-Avatar-root&quot;]/span[@class=&quot;m-104cd71f mantine-Avatar-placeholder&quot;]</value>
      <webElementGuid>95661800-d0c9-4adf-993c-89595e641e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[4]/div/div/span</value>
      <webElementGuid>82bb9a0f-db3f-4873-b80f-b78dbbc9948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::span[1]</value>
      <webElementGuid>b320c878-2fe9-4759-909a-e69244f7727b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VTS'])[1]/following::span[1]</value>
      <webElementGuid>34917cdf-3fcb-4e03-a57c-369650c12155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Settings'])[1]/preceding::span[1]</value>
      <webElementGuid>652bad3c-10b0-4c69-8d2d-cb9f8c77d68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/preceding::span[1]</value>
      <webElementGuid>f850c905-4fcc-430a-ba08-077dd4035b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MP']/parent::*</value>
      <webElementGuid>e00f4a1b-8ea4-4163-bab2-1e6fc01ed980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>f88b901f-d19a-46cc-9387-e4c9abdd5289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Mallika PK' and (text() = 'MP' or . = 'MP')]</value>
      <webElementGuid>ee3836ba-4d28-4079-83d3-07f40b4c49a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
