<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Geofences_icon icon-tabler icon-tabler-plus</name>
   <tag></tag>
   <elementGuidId>d5643d4f-be9f-4998-b40f-d6bde33a3976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.icon.icon-tabler.icon-tabler-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Geofences'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New Geofence Mapping&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>14e27c98-aa9f-486f-8559-911c0d3b7691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>db3faf7c-de67-43ac-a901-8f07963491d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-tabler icon-tabler-plus</value>
      <webElementGuid>c70cc910-889e-41e6-995a-89316ad06526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e77a545d-561a-458f-993d-1e6f5b1cdf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>b38b8fb7-d9da-43a6-be03-4e8b6ec70f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>859b8cb0-ade9-4dbf-8658-8b179db4309b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>0fb5361c-dc85-4ee5-9d56-8d4b9a3d4a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>118e7532-1175-43c2-8173-b64bdf2c28db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6e28559b-b573-43a8-aa29-50114b985446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>b481bed5-e46f-4ba4-b855-8d8c1afc9f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d8b57142-b1be-4de8-b4bb-665c6e416c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;pl-[76px] pb-8&quot;]/div[1]/div[@class=&quot;w-full flex flex-col&quot;]/div[@class=&quot;w-full px-4 grow py-4&quot;]/div[1]/div[@class=&quot;bg-white rounded shadow-soft px-6 py-4 flex flex-col space-y-4 w-full&quot;]/div[@class=&quot;flex justify-between items-center&quot;]/div[@class=&quot;flex flex-row justify-between items-end space-x-4&quot;]/button[@class=&quot;mantine-focus-auto mantine-active m-77c9d27d mantine-Button-root m-87cf2631 mantine-UnstyledButton-root&quot;]/span[@class=&quot;m-80f1301b mantine-Button-inner&quot;]/span[@class=&quot;m-a74036a mantine-Button-section&quot;]/svg[@class=&quot;icon icon-tabler icon-tabler-plus&quot;]</value>
      <webElementGuid>75c6087c-2f46-4521-8370-bb462d8a33c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geofences'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>6ed77fff-f1f6-4c3b-999d-e2a88612f146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d8cb60d2-9432-4c71-a293-955bbf0ec356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Geofence Mapping'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>d581d1ee-8476-45dd-bd02-7014f4f6aff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Truck Vts'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>a45da732-9439-427d-ae81-9c2a71203567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
